name: nsq-nightly-build
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write
env:
  NSQ_REPOSITORY: dudleycarr/nsq
  NSQ_BRANCH: fix-docker-build
jobs:
  stable-meta:
    outputs:
      TAG: ${{ steps.latest-release.outputs.TAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NSQ
        uses: actions/checkout@v4
        with:
          repository: ${{ env.NSQ_REPOSITORY }}
          ref: ${{ env.NSQ_BRANCH }}
          path: nsq
      - name: Get latest stable release tag
        id: latest-release
        run: |
          echo "cd nsq && TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
  stable:
    needs: [stable-meta]
    name: Build latest stable release
    uses: ./.github/workflows/build.yml
    with:
      repository: ${{ env.NSQ_REPOSITORY }}
      ref: ${{ needs.stable-meta.outputs.TAG }}
      release: ${{ needs.stable-meta.outputs.TAG }}
  nightly-meta:
    outputs:
      COMMIT_SHA: ${{ steps.release-id.outputs.COMMIT_SHA }}
      RELEASE_ID: ${{ steps.release-id.outputs.RELEASE_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NSQ
        uses: actions/checkout@v4
        with:
          repository: ${{ env.NSQ_REPOSITORY }}
          ref: ${{ env.NSQ_BRANCH }}
          path: nsq
      - name: Get latest commit to main branch
        id: latest-commit
        run: |
          echo "cd nsq && COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Generate release identifier from date
        id: release-id
        run: |
          echo "RELEASE_ID=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
  nightly:
      needs: [nightly-meta]
      name: Build latest stable release
      uses: ./.github/workflows/build.yml
      with:
        repository: ${{ env.NSQ_REPOSITORY }}
        ref: ${{ needs.nightly-meta.outputs.COMMIT_SHA }}
        release: needs.nightly-meta.outputs.RELEASE_ID }}
