name: nsq-nightly-build
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write
env:
  NSQ_REPOSITORY: dudleycarr/nsq
  NSQ_BRANCH: fix-docker-build
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NSQ
        uses: actions/checkout@v4
        with:
          repository: ${{ env.NSQ_REPOSITORY }}
          ref: ${{ env.NSQ_BRANCH }}
      - name: Get latest stable release tag
        id: latest-release
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Build latest stable release
        uses: ./.github/workflows/build.yml
        with:
          repository: ${{ env.NSQ_REPOSITORY }}
          ref: ${{ steps.latest-release.output.TAG }}
          release: ${{ steps.latest-release.output.TAG }}
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NSQ
        uses: actions/checkout@v4
        with:
          repository: ${{ env.NSQ_REPOSITORY }}
          ref: ${{ env.NSQ_BRANCH }}
      - name: Get latest commit to main branch
        id: latest-commit
        run: |
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Generate release identifier from date
        id: release-id
        run: |
          echo "RELEASE_ID=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Build latest stable release
        uses: ./.github/workflows/build.yml
        with:
          repository: ${{ env.NSQ_REPOSITORY }}
          ref: ${{ env.REF }}
          release: ${{ env.RELEASE }}
