name: Nightly Build
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write
env:
  NSQ_REPOSITORY: ${{ vars.REPOSITORY != "" && vars.RESPOSITORY || "nsqio/nsq" }}
  NSQ_BRANCH: ${{ vars.NSQ_BRANCH != "" && vars.BRANCH || "master" }}
jobs:
  nightly-meta:
    outputs:
      NSQ_REPOSITORY: ${{ steps.latest-commit.outputs.NSQ_REPOSITORY }}
      COMMIT_SHA: ${{ steps.latest-commit.outputs.COMMIT_SHA }}
      RELEASE_ID: ${{ steps.release-id.outputs.RELEASE_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NSQ
        uses: actions/checkout@v4
        with:
          repository: ${{ env.NSQ_REPOSITORY }}
          ref: ${{ env.NSQ_BRANCH }}
      - name: Get latest commit to main branch
        id: latest-commit
        run: |
          echo "NSQ_REPOSITORY=$NSQ_REPOSITORY" >> $GITHUB_OUTPUT
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Generate release identifier from date
        id: release-id
        run: |
          echo "RELEASE_ID=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
  nightly:
      needs: [nightly-meta]
      name: Build nightly release
      uses: ./.github/workflows/build.yml
      with:
        repository: ${{ needs.nightly-meta.outputs.NSQ_REPOSITORY }}
        ref: ${{ needs.nightly-meta.outputs.COMMIT_SHA }}
        release: ${{ needs.nightly-meta.outputs.RELEASE_ID }}
